[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
abi_stable = "0.11.3"
anyrun-plugin = { git = "https://github.com/Kirottu/anyrun" }
serde = { version = "1.0.210", features = ["derive"] }
ron = "0.8.1"
workspace-hack = { version = "0.1", path = "../workspace-hack" }
